import type {Metadata} from "next";
import {ClerkProvider} from "@clerk/nextjs";
import "./globals.scss";
import localFont from "next/font/local";
import {AppUIContextProvider} from "@/context/app.settings";

const Helvetical = localFont({
  src: [
    {
      path: "../../public/fonts/Helvetica.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Helvetica-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica-rounded-bold.woff",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../public/fonts/Helvetica-BoldOblique.woff",
      weight: "900",
      style: "italic",
    },
    {
      path: "../../public/fonts/Helvetica-Oblique.woff",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/helvetica-light.woff",
      weight: "300",
      style: "normal",
    },
  ],
  preload: true,
  variable: "--font-helvetica",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppUIContextProvider>
      <ClerkProvider>
        <html lang="en">
          <body className={`${Helvetical.variable} antialiased`}>
            {children}
          </body>
        </html>
      </ClerkProvider>
    </AppUIContextProvider>
  );
}
